# Generated by Django 6.0.6 on 2026-06-18 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('meter_number', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_category', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], default='Residential', max_length=50)),
                ('connection_type', models.CharField(default='Single Phase', max_length=30)),
                ('geographic_zone', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='VendingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('authorization_status', models.CharField(choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized')], default='Authorized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField()),
                ('cumulative_kwh', models.FloatField()),
                ('meter_status', models.CharField(choices=[('Normal', 'Normal'), ('Tamper', 'Tamper Flag'), ('Bypass', 'Bypass Detected')], default='Normal', max_length=30)),
                ('consumption_delta', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='fraud_app.customer')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('purchased_units', models.FloatField()),
                ('payment_amount', models.FloatField()),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fraud_app.customer')),
                ('vending_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fraud_app.vendingpoint')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Token', 'Token Fraud'), ('Tamper', 'Meter Tampering'), ('Vending', 'Vending Fraud'), ('General', 'General Anomaly')], default='General', max_length=20)),
                ('fraud_probability', models.FloatField()),
                ('investigation_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed Fraud'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('investigation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fraud_app.customer')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fraud_app.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
